matrix:
  include:
    - language: cpp
      compiler: gcc
      env:
        matrix:
          - PLATFORM=windows	BITS=32	TARGET=release_debug	TOOLS=yes
          - PLATFORM=windows	BITS=64	TARGET=release_debug	TOOLS=yes
          - PLATFORM=x11	BITS=32	TARGET=release_debug	TOOLS=yes
          - PLATFORM=x11	BITS=64	TARGET=release_debug	TOOLS=yes
          
          - PLATFORM=windows	BITS=32	TARGET=release_debug	TOOLS=no
          #- PLATFORM=windows	BITS=32	TARGET=release	TOOLS=no
          - PLATFORM=windows	BITS=64	TARGET=release_debug	TOOLS=no
          #- PLATFORM=windows	BITS=64	TARGET=release	TOOLS=no
          - PLATFORM=x11	BITS=32	TARGET=release_debug	TOOLS=no
          #- PLATFORM=x11	BITS=32	TARGET=release	TOOLS=no
          - PLATFORM=x11	BITS=64	TARGET=release_debug	TOOLS=no
          #- PLATFORM=x11	BITS=64	TARGET=release	TOOLS=no
          - PLATFORM=server	BITS=32	TARGET=release_debug	TOOLS=no
          #- PLATFORM=server	BITS=32	TARGET=release	TOOLS=no
          - PLATFORM=server	BITS=64	TARGET=release_debug	TOOLS=no
          #- PLATFORM=server	BITS=64	TARGET=release	TOOLS=no
          - PLATFORM=javascript	TARGET=release_debug	TOOLS=no
          #- PLATFORM=javascript	TARGET=release	TOOLS=no
          #- PLATFORM=bb10	TARGET=release_debug	TOOLS=no
          #- PLATFORM=bb10	TARGET=release	TOOLS=no
          
    - language: objective-c
      env:
        matrix:
          - PLATFORM=osx	TARGET=release_debug	TOOLS=yes
          - PLATFORM=osx	TARGET=release_debug	TOOLS=no
          #- PLATFORM=osx	TARGET=release	TOOLS=no
          - PLATFORM=iphone	TARGET=release_debug	TOOLS=no
          - PLATFORM=iphone	TARGET=release	TOOLS=no
          
    - language: android
      android:
        components:
          - android-8
          - android-13
      jdk: openjdk7
      env:
        matrix:
          - PLATFORM=android	TARGET=release_debug	TOOLS=no
          - PLATFORM=android	TARGET=release	TOOLS=no

#before_install:
#  -
#before_script: 
#  -

script: ./ci/travis-ci.sh

#before_deploy: "EXPORT DEPLOY=yes"
#deploy:

#after_deploy:
#  - ./after_deploy_1.sh
#  - ./after_deploy_2.sh

