#***********************************************************************#
#  .travis.yml.sh                                                       #
#***********************************************************************#
#                       This file is part of:                           #
#                           GODOT ENGINE                                #
#                    http://www.godotengine.org                         #
#***********************************************************************#
# Copyright (c) 2007-2015 Juan Linietsky, Ariel Manzur.                 #
#                                                                       #
# Permission is hereby granted, free of charge, to any person obtaining #
# a copy of this software and associated documentation files (the       #
# "Software"), to deal in the Software without restriction, including   #
# without limitation the rights to use, copy, modify, merge, publish,   #
# distribute, sublicense, and/or sell copies of the Software, and to    #
# permit persons to whom the Software is furnished to do so, subject to #
# the following conditions:                                             #
#                                                                       #
# The above copyright notice and this permission notice shall be        #
# included in all copies or substantial portions of the Software.       #
#                                                                       #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,       #
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF    #
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.#
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  #
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  #
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     #
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                #
#***********************************************************************#

cache:
  - apt
  - ccache
matrix:
  include:
  # [ Linux, Windows, Javascript & Blackberry ]
  - language: cpp
    compiler: gcc
    env: PLATFORM=windows BITS=32 TARGET=release_debug TOOLS=yes
  - language: cpp
    compiler: gcc
    env: PLATFORM=windows BITS=64 TARGET=release_debug TOOLS=yes
  - language: cpp
    compiler: gcc
    env: PLATFORM=x11 BITS=32 TARGET=release_debug TOOLS=yes
  - language: cpp
    compiler: gcc
    env: PLATFORM=x11 BITS=64 TARGET=release_debug TOOLS=yes
  - language: cpp
    compiler: gcc
    env: PLATFORM=windows BITS=32 TARGET=release_debug TOOLS=no
  #- language: cpp
  #  compiler: gcc
  #  env: - PLATFORM=windows BITS=32 TARGET=release TOOLS=no
  - language: cpp
    compiler: gcc
    env: PLATFORM=windows BITS=64 TARGET=release_debug TOOLS=no
  #- language: cpp
  #  compiler: gcc
  #  env: PLATFORM=windows BITS=64 TARGET=release TOOLS=no
  - language: cpp
    compiler: gcc
    env: PLATFORM=x11 BITS=32 TARGET=release_debug TOOLS=no
  #- language: cpp
  #  compiler: gcc
  #  env: PLATFORM=x11 BITS=32 TARGET=release TOOLS=no
  - language: cpp
    compiler: gcc
    env: PLATFORM=x11 BITS=64 TARGET=release_debug TOOLS=no
  #- language: cpp
  #  compiler: gcc
  #  env: PLATFORM=x11 BITS=64 TARGET=release TOOLS=no
  - language: cpp
    compiler: gcc
    env: PLATFORM=server BITS=32 TARGET=release_debug TOOLS=no
  #- language: cpp
  #  compiler: gcc
  #  env: PLATFORM=server BITS=32 TARGET=release TOOLS=no
  - language: cpp
    compiler: gcc
    env: PLATFORM=server BITS=64 TARGET=release_debug TOOLS=no
  #- language: cpp
  #  compiler: gcc
  #  env: PLATFORM=server BITS=64 TARGET=release TOOLS=no
  - language: cpp
    compiler: gcc
    env: PLATFORM=javascript TARGET=release_debug TOOLS=no
  #- language: cpp
  #  compiler: gcc
  #  env: PLATFORM=javascript TARGET=release TOOLS=no
  #- language: cpp
  #  compiler: gcc
  #  env: PLATFORM=bb10 TARGET=release_debug TOOLS=no
  #- language: cpp
  #  compiler: gcc
  #  env: PLATFORM=bb10 TARGET=release TOOLS=no
  
  # [ MacOSX & iOS ]
  - language: objective-c
    os: osx
    env: PLATFORM=osx TARGET=release_debug TOOLS=yes
  - language: objective-c
    os: osx
    env: PLATFORM=osx TARGET=release_debug TOOLS=no
  #- language: objective-c
  #  os: osx
  #  env: PLATFORM=osx TARGET=release TOOLS=no
  - language: objective-c
    os: osx
    env: PLATFORM=iphone TARGET=release_debug TOOLS=no
  - language: objective-c
    os: osx
    env: PLATFORM=iphone TARGET=release TOOLS=no
  
  # [ Android ]
  - language: android
    android:
      components:
        - android-8
        - android-13
    jdk: openjdk7
    env: PLATFORM=android TARGET=release_debug TOOLS=no
  - language: android
    android:
      components:
        - android-8
        - android-13
    jdk: openjdk7
    env: PLATFORM=android TARGET=release TOOLS=no

before_install:
  - sudo bash -c 'mkdir -p /usr/local/cached && chmod 775 /usr/local/cached'
install:
  - sudo bash ci/travis-ci/dependencies.sh $PLATFORM $BITS
before_script:
  - bash ci/travis-ci/prepare.sh
script:
  - bash ci/travis-ci/build.sh
#before_deploy: "EXPORT DEPLOY=yes"
#deploy: bash ci/travis-ci/deploy.sh
#after_deploy:
#  - ./after_deploy_1.sh
#  - ./after_deploy_2.sh
